language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa && sudo apt-get update -qq && sudo apt-get install -y qt5-qmake qtbase5-dev qtdeclarative5-dev; fi

script: 
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make

os:
  - linux
